const PROJECT = {
  basic: {
    name:'BASIC', controller:'Arduino Uno', drive:'2WD Differential', motors:2, drivers:1,
    channels:[['CH1','Steering'],['CH2','Throttle'],['CH5','Kicker']],
    pins:[['CH1','D2'],['CH2','D3'],['CH5','A0'],['PWMA','D5'],['AIN1 / AIN2','D7 / D8'],['PWMB','D6'],['BIN1 / BIN2','D9 / D10'],['STBY','D4'],['Kicker servo','A3']],
    image:'assets/basic_wiring.svg', firmware:'https://github.com/nashihab/OpenSoccerBot/blob/main/src/basic_uno/basic_uno_rc.ino',
    flow:['RC transmitter','RC receiver','Arduino Uno','TB6612FNG','2 motors + kicker'],
    wiring:['RC CH1 → D2','RC CH2 → D3','RC CH5 → A0','Motor A → D5/D7/D8','Motor B → D6/D9/D10','Kicker → A3'],
    steps:['Assemble rigid 2WD chassis','Mount motors and wheels','Wire TB6612FNG + receiver + Uno','Install fuse, switch and regulated 5 V rail','Attach kicker servo','Upload firmware and calibrate RC','Run wheel-off-ground test before field test']
  },
  advanced: {
    name:'ADVANCED', controller:'ESP32 DevKit', drive:'4WD Mecanum', motors:4, drivers:2,
    channels:[['CH1','Strafe'],['CH2','Forward / Reverse'],['CH4','Rotate'],['CH5','Kicker'],['CH6','Dribbler']],
    pins:[['CH1 / CH2 / CH4','GPIO 34 / 35 / 36'],['CH5 / CH6','GPIO 39 / 13'],['FL PWM / IN1 / IN2','25 / 4 / 16'],['FR PWM / IN1 / IN2','26 / 17 / 18'],['RL PWM / IN1 / IN2','27 / 19 / 21'],['RR PWM / IN1 / IN2','14 / 22 / 23'],['Kicker servo','GPIO 32'],['Dribbler gate','GPIO 33']],
    image:'assets/advanced_wiring.svg', firmware:'https://github.com/nashihab/OpenSoccerBot/blob/main/src/advanced_esp32/advanced_esp32_rc.ino',
    flow:['RC transmitter','RC receiver','ESP32','2 × TB6612FNG','4 motors + kicker + dribbler'],
    wiring:['RC CH1/2/4 → GPIO 34/35/36','RC CH5/6 → GPIO 39/13','Front driver → GPIO 25/4/16 + 26/17/18','Rear driver → GPIO 27/19/21 + 14/22/23','Kicker → GPIO 32','Dribbler MOSFET → GPIO 33'],
    steps:['Assemble rigid 4WD chassis','Mount four mecanum wheels with correct handedness','Wire two TB6612FNG boards + ESP32','Install receiver, kicker and dribbler stage','Build the protected 2S/3S power system','Upload firmware and calibrate channels','Test each direction, then tune mecanum response']
  }
};
const COMPONENTS=[
 ['Arduino Uno','MCU','BASIC','ATmega328P 5 V controller'],['ESP32 DevKit','MCU','ADVANCED','Manual RC control + mecanum mixing'],['TB6612FNG','Drive','BOTH','Dual brushed-motor H-bridge'],['DC geared motor','Drive','BOTH','Select voltage/current to match the driver'],['Mecanum wheel','Drive','ADVANCED','Correct mirrored roller orientation required'],['RC receiver','Control','BOTH','PWM is the base interface'],['RC transmitter','Control','BOTH','FlySky FS-i6/i6X is one reference option'],['Servo','Mechanism','BOTH','Kicker mechanism'],['Brushed DC motor + MOSFET','Mechanism','ADVANCED','Dribbler'],['Buck/BEC 5 V','Power','BOTH','Regulated logic / receiver / servo rail'],['Fuse + master switch','Safety','BOTH','Place protection close to the battery']
];
let mode='advanced', wiringIndex=0, componentFilter='ALL', axes={a:0,b:0,c:0,d:0};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function setMode(m){mode=m; document.body.dataset.mode=m; $$('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===m)); $('#canvasMode').textContent=PROJECT[m].name; renderAll();}
function renderAll(){renderStats();renderFlow();renderWiring();renderHardware();renderFirmware();renderSteps();renderControl();drawRobot();}
function renderStats(){const c=PROJECT[mode]; $('#heroStats').innerHTML=`<div class="stat"><span>Controller</span><b>${c.controller}</b></div><div class="stat"><span>Drive</span><b>${c.drive}</b></div><div class="stat"><span>Motors</span><b>${c.motors}</b></div><div class="stat"><span>Motor drivers</span><b>${c.drivers} × TB6612</b></div>`;}
function renderFlow(){ $('#flow').innerHTML=PROJECT[mode].flow.map((x,i)=>`<div class="flow-node"><span>0${i+1}</span>${x}</div>${i<PROJECT[mode].flow.length-1?'<div class="flow-arrow">↓</div>':''}`).join(''); }
function renderWiring(){const c=PROJECT[mode];$('#wiringImage').src=c.image;$('#wiringMenu').innerHTML=c.wiring.map((x,i)=>`<button class="${i===wiringIndex?'selected':''}" data-wiring="${i}"><span>${String(i+1).padStart(2,'0')}</span>${x}</button>`).join('');$$('[data-wiring]').forEach(b=>b.onclick=()=>{wiringIndex=+b.dataset.wiring;renderWiring()});const p=c.pins[wiringIndex%c.pins.length];$('#wireTitle').textContent=c.wiring[wiringIndex];$('#wireDetail').innerHTML=`${p[0]} → <code>${p[1]}</code>`;}
function updateBattery(){const s=Math.max(1,Math.min(4,+$('#series').value||1)),p=Math.max(1,Math.min(6,+$('#parallel').value||1)),cap=Math.max(500,+$('#cellCap').value||500),nom=s*3.7,full=s*4.2,pack=cap*p,wh=nom*pack/1000;$('#batteryReadout').innerHTML=`<div><span>Pack</span><strong>${s}S${p}P</strong></div><div><span>Nominal</span><strong>${nom.toFixed(1)} V</strong></div><div><span>Full</span><strong>${full.toFixed(1)} V</strong></div><div><span>Capacity</span><strong>${pack} mAh</strong></div><div><span>Energy</span><strong>${wh.toFixed(1)} Wh</strong></div>`;const st=$('#batteryStatus');st.className=s<=3?'success':'warning';st.textContent=s<=3?'✓ Within the 2S/3S voltage range used by the documented TB6612 builds.':'⚠ 4S is not suitable for the documented TB6612FNG VM range. Use a different motor driver stage.';}
function renderControl(){const adv=mode==='advanced';$('#stick1Label').textContent=adv?'STRAFE':'STEERING';$('#stick2Label').textContent=adv?'ROTATE':'THROTTLE';$('#stick1y').textContent=adv?`Y ${axes.b.toFixed(2)}`:'Y —';$('#stick2x').textContent=adv?`X ${axes.c.toFixed(2)}`:`X ${axes.b.toFixed(2)}`;$('#stick2y').textContent='Y —';const vals=adv?[axes.b+axes.a+axes.c,axes.b-axes.a-axes.c,axes.b-axes.a+axes.c,axes.b+axes.a-axes.c]:[axes.b+axes.a,axes.b-axes.a];const names=adv?['FL','FR','RL','RR']:['LEFT','RIGHT'];const max=Math.max(1,...vals.map(v=>Math.abs(v)));$('#motorRows').innerHTML=vals.map((v,i)=>{const n=v/max,p= Math.abs(n)*100;const left=n<0?`${50-p/2}%`:`50%`;return `<div class="motor-row"><span>${names[i]}</span><div class="bar"><i style="width:${p}%;left:${left};transform:${n<0?'':'none'}"></i></div><strong>${Math.round(n*100)}%</strong></div>`}).join('');$('#driveLabel').textContent=PROJECT[mode].drive;$('#driveOrder').textContent=adv?'FL · FR · RL · RR':'LEFT · RIGHT';$('#formula').textContent=adv?'FL = Y + X + R · FR = Y − X − R · RL = Y − X + R · RR = Y + X − R':'';updateKnobs();}
function updateKnobs(){const map=[['#stick1',axes.a,axes.b],['#stick2',mode==='advanced'?axes.c:axes.b,0]];map.forEach(([sel,x,y])=>{const k=$(sel+' .stick-knob');k.style.left=`${50+x*45}%`;k.style.top=`${50-y*45}%`});$('#stick1x').textContent=`X ${axes.a.toFixed(2)}`;$('#stick1y').textContent=mode==='advanced'?`Y ${axes.b.toFixed(2)}`:'Y —';}
function bindStick(id,onMove){const e=$(id);const move=(ev)=>{const r=e.getBoundingClientRect(),x=Math.max(-1,Math.min(1,((ev.clientX-r.left)/r.width-.5)*2)),y=Math.max(-1,Math.min(1,((ev.clientY-r.top)/r.height-.5)*-2));onMove(x,y);renderControl()};e.addEventListener('pointerdown',ev=>{e.setPointerCapture(ev.pointerId);move(ev)});e.addEventListener('pointermove',ev=>{if(e.hasPointerCapture(ev.pointerId))move(ev)});}
function renderHardware(){const filters=['ALL','MCU','Drive','Control','Mechanism','Power','Safety'];$('#chipRow').innerHTML=filters.map(f=>`<button class="chip ${f===componentFilter?'active':''}" data-filter="${f}">${f}</button>`).join('');$$('[data-filter]').forEach(b=>b.onclick=()=>{componentFilter=b.dataset.filter;renderHardware()});const rows=COMPONENTS.filter(c=>(componentFilter==='ALL'||c[1]===componentFilter)&&(c[2]==='BOTH'||c[2]===PROJECT[mode].name));$('#componentGrid').innerHTML=rows.map(c=>`<article class="component"><div class="component-top"><span>${c[1]}</span><b>${c[0]}</b></div><p>${c[3]}</p><small>${c[2]==='BOTH'?'BASIC + ADVANCED':c[2]}</small></article>`).join('');}
function renderFirmware(){const adv=mode==='advanced';$('#firmwareSource').textContent=`Source: ${PROJECT[mode].firmware}`;const blocks=adv?[['RC input','CH1 strafe · CH2 forward · CH4 rotate · CH5 kick · CH6 dribbler'],['Mecanum mix','FL = Y + X + R · FR = Y − X − R · RL = Y − X + R · RR = Y + X − R'],['Failsafe','invalid / missing drive pulses stop drive and dribbler'],['Mechanisms','servo kicker + MOSFET-switched dribbler']]:[['RC input','CH1 steering · CH2 throttle · CH5 kicker'],['Differential drive','left = throttle + steering · right = throttle − steering'],['Failsafe','invalid / missing drive pulses stop the motors'],['Kicker','servo pulse with cooldown + drive lockout']];$('#firmwareGrid').innerHTML=blocks.map(x=>`<div><span>${x[0]}</span><p>${x[1]}</p></div>`).join('');$('#codeMini').textContent=adv?`float fl = forward + strafe + rotate;\nfloat fr = forward - strafe - rotate;\nfloat rl = forward - strafe + rotate;\nfloat rr = forward + strafe - rotate;`:`long left = (long)throttle + steering;\nlong right = (long)throttle - steering;`;$('#firmwareLink').href=PROJECT[mode].firmware;}
function renderSteps(){$('#steps').innerHTML=PROJECT[mode].steps.map((x,i)=>`<div class="step"><span>${String(i+1).padStart(2,'0')}</span><p>${x}</p></div>`).join('');}
function drawRobot(){const c=$('#robotCanvas'),ctx=c.getContext('2d'),dpr=Math.min(devicePixelRatio||1,2);const rect=c.getBoundingClientRect();const w=rect.width*dpr,h=rect.height*dpr;if(c.width!==w||c.height!==h){c.width=w;c.height=h}ctx.save();ctx.scale(dpr,dpr);const W=rect.width,H=rect.height;ctx.clearRect(0,0,W,H);const cx=W/2,cy=H/2+10,adv=mode==='advanced';ctx.save();ctx.translate(cx,cy);ctx.rotate(axes.view||-0.16);const L=adv?300:250,R=adv?210:150;ctx.shadowColor='rgba(0,0,0,.35)';ctx.shadowBlur=30;ctx.shadowOffsetY=18;ctx.fillStyle='#1b2a40';roundRect(ctx,-L/2,-R/2,L,R,20,true);ctx.shadowColor='transparent';ctx.fillStyle='#0a1019';roundRect(ctx,-L/2+30,-R/2+30,L-60,R-60,14,true);ctx.fillStyle='#263d59';roundRect(ctx,-62,-42,124,84,10,true);ctx.fillStyle='#2a83ff';roundRect(ctx,-26,-18,52,36,8,true);ctx.fillStyle='#f0c54f';roundRect(ctx,-47,R/2-18,94,12,6,true);const wheels=adv?[[-L/2-12,-R/2+54],[-L/2-12,R/2-54],[L/2+12,-R/2+54],[L/2+12,R/2-54]]:[[-L/2-12,0],[L/2+12,0]];wheels.forEach(([x,y],i)=>{ctx.save();ctx.translate(x,y);ctx.fillStyle=adv?'#e4b63d':'#d9e0ea';roundRect(ctx,-18,-38,36,76,12,true);ctx.fillStyle='#222d3c';roundRect(ctx,-7,-24,14,48,6,true);if(adv){ctx.strokeStyle='#5ab1ff';ctx.globalAlpha=.55;for(let a=-20;a<=20;a+=10){ctx.beginPath();ctx.moveTo(-13,a);ctx.lineTo(13,a+12);ctx.stroke()}}ctx.restore()});ctx.fillStyle='#1d2939';ctx.font='700 14px system-ui';ctx.textAlign='center';ctx.fillText(adv?'ESP32':'ARDUINO UNO',0,-2);ctx.fillStyle='#9bb0c8';ctx.font='11px system-ui';ctx.fillText(adv?'4WD MECANUM':'2WD DIFFERENTIAL',0,70);ctx.restore();ctx.restore();}
function roundRect(ctx,x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill)ctx.fill()}
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#series').oninput=updateBattery;$('#parallel').oninput=updateBattery;$('#cellCap').oninput=updateBattery;bindStick('#stick1',(x,y)=>{axes.a=x; if(mode==='advanced')axes.b=y; else axes.a=x;});bindStick('#stick2',(x,y)=>{if(mode==='advanced')axes.c=x;else axes.b=x});let dragging=false,lastX=0;const rc=$('#robotCanvas');rc.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;rc.setPointerCapture(e.pointerId)});rc.addEventListener('pointermove',e=>{if(!dragging)return;axes.view=(axes.view||-0.16)+(e.clientX-lastX)*0.01;lastX=e.clientX;drawRobot()});rc.addEventListener('pointerup',()=>dragging=false);rc.addEventListener('pointercancel',()=>dragging=false);window.addEventListener('resize',drawRobot);setMode('advanced');updateBattery();
